### PR TITLE
fixing OS dependent issue

### LINKED ISSUE #9: OS dependent issue
the original `gendr()` fails to extract default values for `languages` and `locations` when they are `NULL`, returning NAs when it shouldn't: 

This behavior does not appear on Windows OS while it has not been tested on Linux. 

``` r
gendr <- function(names = NULL, locations = NULL, languages = NULL, 
                  years = NULL, methods = "standard"){
        if(is.null(names)){
                names <- Sys.info()["user"]
        }
        if(is.null(locations)){
                lc <- strsplit(strsplit(Sys.getlocale(), "=")[[1]][2], "\\.")[[1]][1]
                locations <- strsplit(lc, "_")[[1]][2]
        }
        if(is.null(languages)){
                lc <- strsplit(strsplit(Sys.getlocale(), "=")[[1]][2], "\\.")[[1]][1]
                languages <- strsplit(lc, "_")[[1]][1]
        }
        if(is.null(years)){
                years <- as.numeric(format(Sys.time(), "%Y"))
        }
        if(!is.character(names)){
                stop("`names` must be characters", call. = FALSE)
        }
        if(!is.character(languages)){
                stop("`languages` must be characters", call. = FALSE)
        }
        if(!is.character(locations)){
                stop("`locations` must be characters", call. = FALSE)
        }
        if(!is.character(methods)){
                stop("`methods` must be characters", call. = FALSE)
        }
        if(!is.numeric(years) || any(years %% 1 != 0)){
                stop("`years` must be integer conformable numbers", call. = FALSE)
        }
        gendr_warning()
        expand.grid(name = names, location = locations, language = languages, 
                    method = methods, year = years, gender = "?")
}

gendr_warning <- function(){
        msgs <- c("assigning a gender to someone else is an act of violence",
                  "gender is not a binary",
                  "if it is important to know someone's gender, ask them",
                  "assigning genders is inherently inaccurate",
                  "gender is an evolving and variable human construct",
                  "consider the impact on individuals for whom your assumptions are wrong")
        warning(sample(msgs, 1), call. = FALSE, immediate. = TRUE)
}

gendr()
#> Warning: gender is an evolving and variable human construct
#>    name location language   method year gender
#> 1 kings     <NA>     <NA> standard 2019      ?
```

<sup>Created on 2019-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Sierra 10.12.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Asia/Shanghai               
#>  date     2019-11-03                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                         
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                 
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.0)                 
#>  callr         3.3.2      2019-09-22 [1] CRAN (R 3.6.0)                 
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                 
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                 
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                 
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.0)                 
#>  digest        0.6.22     2019-10-21 [1] CRAN (R 3.6.0)                 
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.0)                 
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                 
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                 
#>  glue          1.3.1.9000 2019-11-01 [1] Github (tidyverse/glue@995e13f)
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                 
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.0)                 
#>  knitr         1.25       2019-09-18 [1] CRAN (R 3.6.0)                 
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                 
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                 
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.0)                 
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)                 
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                 
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.0)                 
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                 
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                 
#>  Rcpp          1.0.2      2019-07-25 [1] CRAN (R 3.6.0)                 
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                 
#>  rlang         0.4.1      2019-10-24 [1] CRAN (R 3.6.0)                 
#>  rmarkdown     1.16       2019-10-01 [1] CRAN (R 3.6.0)                 
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                 
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.0)                 
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                 
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                 
#>  testthat      2.2.1      2019-07-25 [1] CRAN (R 3.6.0)                 
#>  usethis       1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                 
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                 
#>  xfun          0.10       2019-10-01 [1] CRAN (R 3.6.0)                 
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                 
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

### PR DESCRIPTION
**Pull request by chuckleong21**
Fixes #9

### CODE REVIEW

**Review by juniperlsimonis — CHANGES_REQUESTED** [review]
oh, thanks much for catching this!
can you please edit your code so that only the altered lines are replaced? (a lot of lines are replaced only due to space/indentation edits that shouldn't be happening). 
also, would you like to be added as a contributor to the author list?

**Comment by chuckleong21** [comment]
Hi, do bear with me for this is me pulling a request for the first time. I was worried that I broke your code so I copied and pasted most of the old script. I'll pay attention from now on. I added the `%||%` for a change to increase code readability and reduce repetitions.

Yes, I would like to be added as a contributor. This is a clever package.

**Comment by juniperlsimonis** [comment]
this is great, thanks for your work on this.
can you verify that my edits work for you?
i used what you had, but expanded it's application with a tighter call set, based on what i've found about OSs and the LC variable separating character.
i also took the opportunity to bring over a function i had written elsewhere already that does what the utility you wrote does, but with an explicit name.

**Comment by juniperlsimonis** [comment]
also i added you in as a collaborator under the name "Chuck Leong", let me know if that's ok or if it should be something else. and i can attach it to an ORCID if you have one, just let me know.

**Comment by chuckleong21** [comment]
get_locale() does not work on MacOS for the same reason, mainly because of the different results return from different OS:

Mac: 
``` r
Sys.getlocale()

#> [1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"
```

Windows:
```r
Sys.getlocale()

># [1] "LC_CTYPE=de_DE.UTF-8;LC_NUMERIC=C;LC_TIME=de_DE.UTF-8;
># LC_COLLATE=de_DE.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=de_DE.UTF-8;
># LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=de_DE.UTF-8;
># LC_IDENTIFICATION=C"
```

I believe it is best to relax the condition on calling `get_locale()` since the goal here is to _just_ extract language and location. So what we need is the string separated by "_": "en_US" / "de_DE" being language_location. `countrycode::countrycode()` may be needed to next convert abbreviations into full country/language names.

**Comment by juniperlsimonis** [comment]
ahh, thank you for checking, i didn't realize that macOS wasn't including the variable names in the strings. i've made it now so that the category/variable name (which LC) is used as an argument in `Sys.getlocale()` instead, which should be platform independent. can you try that again?

**Comment by chuckleong21** [comment]
Ah. You beat me to it. I was trying to add an`asis` param to `get_locale()` so the raw locale strings from Mac are properly translated. e.g. **en -> English** and **US -> United States of America** with `translateR:::languageCodes()` and `countrycode::countrycode()`. Overall, the new gendr() works on Mac. 

Few more things upon closing: 
- it is good for concentrating on the package's philosophy by NOT exporting most of the functions in utilites.R, since `ifnull()` and `check_type()` are quite self-explanatory. Plus, it saves you effort maintaining the documentations.
- Yes, Chuck Leong is fine and I don't have an ORCID. (wish I had one)

**Comment by juniperlsimonis** [comment]
great, thanks!
oh, don't close the PR, we need to merge it in. i'll reopen and merge.
the translation to the full names from the ISO names (2-letter) is a little more tricky, actually, so for the time being (in this pr), let's not worry about that, and i'll open an issue for it.
actually, I disagree on the exportation of functions. i understand the pros/cons of both sides of this and work in packages written both ways, but as the package's maintainer, this is my call, and all functions should be documented and exported.

**Review by juniperlsimonis — APPROVED** [review]

**Pull request merged**
