### PR TITLE
[Wip] issue #12

### PR DESCRIPTION
**Pull request by chuckleong21**
Changes made in file to address issue #12:

- Imports `countrycode::countrycode` in NAMESPACE and DESCRIPTION;
- added a param to turn on/off the expansion of ISO name in `get_locale()`;
- added object `language_codes` modified from `translateR`;
- added language_codes.Rd;
- edited get_locale.Rd, gendr.Rd for highlighting this change

Does this look okay to you? Do let me know if you have an alternative approach.

### CODE REVIEW

**Review by juniperlsimonis — CHANGES_REQUESTED** [review]
thanks for this. this isn't really a critical aspect of the code, but i appreciate your work on it. 
a few important notes:
-the checks on travis are failing at the build stage, so there's definitely some work you'd need to do to get that passing
-please don't reformat existing code/comments
-please use snake_case for all objects
-please limit code lines to 80 characters
-when explicitly importing functions, you don't need to reference their home package
-the locales are only long with windows, the way you have it, it assumes all non-mac/solaris are long. on that, you should use the os evaluations instead of the splitting character to determine the os.
-language_codes does not need to be an object outside of functions

i apologize that i don't have a style guide here, but please follow the existing conventions

**Comment by chuckleong21** [comment]
- R CMD CHECK via Rstudio is successful, but not via Terminal:
``` r
## rstudio: 00install.out
* installing *source* package ‘gendrendr’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (gendrendr)

## rstudio: 00check.log
* using log directory ‘/Users/kings/Desktop/R/R projects/gendrendr.Rcheck’
* using R version 3.6.0 (2019-04-26)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘gendrendr/DESCRIPTION’ ... OK
* this is package ‘gendrendr’ version ‘0.1.5’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘gendrendr’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
** found \donttest examples: check also with --run-donttest
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... OK
  Running ‘testthat.R’
* DONE
Status: OK

## Terminal: R CMD CHECK:
* using log directory ‘/Users/kings/Desktop/R/R projects/gendrendr/gendrendr.Rcheck’
* using R version 3.6.0 (2019-04-26)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘gendrendr/DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
* DONE
Status: 1 ERROR
```
Yet the mentioned fields are not empty. I am guessing this is where travis-ci build fails, too. 

- I do think about what your coding style is like when I was making changes to the files. I use RStudio and git to tighten the workflow this time, so I may messed up the format when I reflowed the comment in the roxygen skeleton. What would you suggest me to do?
- I admit it's a bad habit nesting multiple functions in one call.
- I forgot to remove the Namespace for calling a function after importing it explicitly. 
- Tests failed on Windows platform so added the `splitchar` condition.
- About langauge_codes, I feel it is internal in the sense of usage so I did not `@export` it then I mentioned it in documentations. May I know why you want to export it instead of 'hiding' it in `:::`?
- All in all, I just wanted to show you the logic of expansion for ISO names and wondered if it was plausible to you as well. At the point of the time being, it is not worth keeping this branch so I suggest removing it entirely (as I have yet figured out what's causing the failing check on travis). 

I apologize for any inconvenience caused and appreciate you let me collaborate on this project.

**Comment by juniperlsimonis** [comment]
i'm surprised you're ever getting a successful build, as the issue looks like your `DESCRIPTION` file is missing the importation of the `translateR` package
my specific suggestions re: code style are in the previous comment 
i understand that there's a difference based on OS, but my comment was to use the OS checks that are built in already (`ismac` for example) rather than using the downstream `splitchar`, as the characters that split the text do not align 1:1 with the OS-based issue here
i didn't say i wanted `language_codes` exported, i said it shouldn't be an object outside of functions, imported/exported aside.

**Comment by chuckleong21** [comment]
Hi, I edited the files per your suggestion:
- Changed param to `localeAsis` to `locale_asis` in get_locale()
- Made sure code line does not exceed 80 characters
- Placed object `language_codes` inside the function (Though it advises against calling internal objects from a package so I sorta hard-coding the ISO language codes and their names. Therefore there's no need to import anything from `translateR` worrying about unexpected consequences.)
- Deleted language_codes.Rd
- Edited gendr.Rd following the change of param in get_locale

The latest commit on `WIP]-issue-#12` passed the build checks from the build result I had triggered on my travis account. But some of the old commits still fail.

**Comment by juniperlsimonis** [comment]
hi. i don't think that hard-coding the country codes is at all appropriate here, and it is definitely not the right idea to base it on one schema (you chose Google's english output).  for example, in rendering the names of the countries outward, it is important to consider the reader's language, and not just write the country name as if an english speaker in america is using the function. the code you've written up here is very fragile and specific, and is also a large increase in code volume. 

it seems like (from what i've read on this subject over the past few days), that this is much more of a complex issue than i think is necessary to address as part of this package. 

i appreciate your work on this, but i don't anticipate integrating this component of the codebase, unless a more robust and tidier alternative comes around. if this is a worthwhile venture for you, i would consider starting your own package to work on this issue specifically, as it's likely to have a much broader interest than this package here.

**Comment by chuckleong21** [comment]
Hard coding is actually the 'last resort' to address issue #12 since importing an internal object from the package `translateR` causes an unexpected glitch. It is indeed very nice to convert iso language codes into full names, but this seems more trouble than worth up to this point. I do agree it is complex and I feel it starts to sway from the goal of this package.

While hard coding does not seem friendly, the function does work on MacOS platform, either being _en_ or other language locales.

**Comment by chuckleong21** [comment]
Decided to close this as such feature is not worth implementing.

**Pull request closed without merging**
